port the simplified SDC code paths to C++
starkiller-astro/Microphysics pull request #389
Opened 2020-09-02 18:58 UTC by zingale

2020-10-16 14:33 UTC, zingale commented
This is the comparison using the `test_sdc` unit test with the analytic Jacobian:

```
            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                          0                         0
 temperature                                      0                         0
 Xnew_helium-4                       0.001035779219            0.001404248161
 Xnew_carbon-12                       0.00158398835            0.002261791238
 Xnew_oxygen-16                       0.00230380774            0.003278644111
 Xnew_neon-20                        0.001234894186             0.01293670506
 Xnew_magnesium-24                  0.0008210529934             0.00765519585
 Xnew_silicon-28                     0.002610161925            0.004625547772
 Xnew_sulfur-32                     0.0007845679383            0.002718962978
 Xnew_argon-36                      0.0005789155643            0.004190719403
 Xnew_calcium-40                     0.001665069292            0.003159013831
 Xnew_titanium-44                   8.221540895e-05           0.0007608725504
 Xnew_chromium-48                   0.0003886119736            0.003489393032
 Xnew_iron-52                        0.001763213638            0.008719931774
 Xnew_nickel-56                      0.002096329272            0.002776734324
 Xold_helium-4                                    0                         0
 Xold_carbon-12                                   0                         0
 Xold_oxygen-16                                   0                         0
 Xold_neon-20                                     0                         0
 Xold_magnesium-24                                0                         0
 Xold_silicon-28                                  0                         0
 Xold_sulfur-32                                   0                         0
 Xold_argon-36                                    0                         0
 Xold_calcium-40                                  0                         0
 Xold_titanium-44                                 0                         0
 Xold_chromium-48                                 0                         0
 Xold_iron-52                                     0                         0
 Xold_nickel-56                                   0                         0
 wdot_helium-4                        8.3401343e+10            0.002463515993
 wdot_carbon-12                     5.471429111e+10           0.0007818576507
 wdot_oxygen-16                      2.30380774e+11             0.00329471055
 wdot_neon-20                       8.795608678e+10             0.01466093903
 wdot_magnesium-24                  7.261196821e+10             0.01225743111
 wdot_silicon-28                    2.221709764e+11             0.00453254665
 wdot_sulfur-32                     7.366731866e+10             0.00275895277
 wdot_argon-36                      3.132914618e+10            0.003463089221
 wdot_calcium-40                    9.010847602e+10              0.0122057113
 wdot_titanium-44                        2407797106           0.0004087583634
 wdot_chromium-48                   3.886119736e+10            0.006990703276
 wdot_iron-52                       1.763213638e+11             0.03891396413
 wdot_nickel-56                     2.096329272e+11            0.006431988401
 rho_Hnuc                            1.20743678e+29            0.001875561468
```

2020-10-16 14:33 UTC, zingale commented
and here's the number of RHS evals:

Fortran:
```
Run time = 9.755592137
min number of rhs calls: 6
avg number of rhs calls: 186
max number of rhs calls: 3000
```

C++
```
Run time = 2.502314575
min number of rhs calls: 6
avg number of rhs calls: 47
max number of rhs calls: 552
```

2020-10-16 14:37 UTC, zingale commented
With the numerical Jacobian, we have:

C++:
```
Run time = 3.156233457
min number of rhs calls: 21
avg number of rhs calls: 69
max number of rhs calls: 607
```

Fortran:
```
Run time = 10.79592282
min number of rhs calls: 21
avg number of rhs calls: 239
max number of rhs calls: 3613
```

comparison:
```
            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                          0                         0
 temperature                                      0                         0
 Xnew_helium-4                       0.001035995735              0.0014045417
 Xnew_carbon-12                      0.001584528839            0.002262563007
 Xnew_oxygen-16                      0.002303494261            0.003278197987
 Xnew_neon-20                        0.001235135177             0.01293922952
 Xnew_magnesium-24                   0.000821238865            0.007656926439
 Xnew_silicon-28                      0.00261071045            0.004626513864
 Xnew_sulfur-32                     0.0007850241623            0.002720541664
 Xnew_argon-36                      0.0005803704957            0.004201251592
 Xnew_calcium-40                     0.001666114003            0.003160995886
 Xnew_titanium-44                   8.225082934e-05            0.000761200352
 Xnew_chromium-48                   0.0003885693148            0.003489009975
 Xnew_iron-52                        0.001762979113            0.008718695019
 Xnew_nickel-56                      0.002096057016             0.00277637253
 Xold_helium-4                                    0                         0
 Xold_carbon-12                                   0                         0
 Xold_oxygen-16                                   0                         0
 Xold_neon-20                                     0                         0
 Xold_magnesium-24                                0                         0
 Xold_silicon-28                                  0                         0
 Xold_sulfur-32                                   0                         0
 Xold_argon-36                                    0                         0
 Xold_calcium-40                                  0                         0
 Xold_titanium-44                                 0                         0
 Xold_chromium-48                                 0                         0
 Xold_iron-52                                     0                         0
 Xold_nickel-56                                   0                         0
 wdot_helium-4                      8.340846766e+10            0.002463726719
 wdot_carbon-12                     5.471808095e+10           0.0007819118527
 wdot_oxygen-16                     2.303494261e+11            0.003294261835
 wdot_neon-20                       8.796564585e+10             0.01466253238
 wdot_magnesium-24                  7.260360638e+10             0.01225601959
 wdot_silicon-28                    2.221429685e+11            0.004531980393
 wdot_sulfur-32                      7.36582012e+10            0.002758625107
 wdot_argon-36                      3.140788264e+10            0.003471817685
 wdot_calcium-40                    9.016501263e+10             0.01221337071
 wdot_titanium-44                        2408834443           0.0004089344769
 wdot_chromium-48                   3.885693148e+10            0.006989919105
 wdot_iron-52                       1.762979113e+11             0.03890876539
 wdot_nickel-56                     2.096057016e+11            0.006431143309
 rho_Hnuc                           1.207688175e+29            0.001875951684
```

2020-10-20 20:22 UTC, harpolea requested changes
This mostly looks ok to me (or at least equivalent to the Fortran),  except for the stuff I flagged in `vode_type_simplified_sdc.H`

2020-10-20 20:22 UTC, harpolea commented on integration/VODE/vode_type_simplified_sdc.H
> +  Real X_dedX_sum = 0.0;
```suggestion
  Real X_dedX_sum = 0.0_rt;
```

2020-10-20 20:22 UTC, harpolea commented on integration/VODE/vode_type_simplified_sdc.H
> +  eos_state.T = 1.e4;   // initial guess
```suggestion
  eos_state.T = 1.e4_rt;   // initial guess
```

2020-10-20 20:22 UTC, harpolea commented on integration/VODE/vode_type_simplified_sdc.H
> +    eos_state.xn[n] = vode_state.y(SFS+n) / state.rho;
```suggestion
    eos_state.xn[n] = vode_state.y(SFS+1+n) / state.rho;
```

2020-10-20 20:22 UTC, harpolea commented on integration/VODE/vode_type_simplified_sdc.H
> +    (state.rho * eos_state.dhdT);
```suggestion
  Real X_dhdX_sum = 0.0;
  for (int n = 0; n < NumSpec; n++) {
    X_dhdX_sum += eos_state.xn[n] * eos_xderivs.dhdX[n];
  }
  dwdU(iwT, SRHO_EXTRA+1) =
    (X_dhdX_sum - state.rho * eos_state.dhdr - eos_state.h) /
    (state.rho * eos_state.dhdT);
```

I think this should use `dhdX` here instead of `dedX`

2020-10-20 23:16 UTC, zingale commented on integration/VODE/vode_type_simplified_sdc.H
> +  ydot(SEINT+1) += state.rho * ydot_react(net_ienuc);
yes, net_itemp and net_ienuc are 1-based (defined in burn_type.H), and ydot_react is 1-based.

2020-10-20 23:18 UTC, zingale commented on integration/VODE/vode_type_simplified_sdc.H
> +     vode_state.y(SFS+n) = amrex::max(amrex::min(vode_state.y(SFS+n), state.rho),
SRHO is not defined for SDC_EVOLVE_ENTHALPY, so I make sure that we always define state.rho regardless of which system we are evolving.

2020-10-21 12:55 UTC, harpolea approved these changes

2020-10-21 14:18 UTC, merged